Revert "net: fix bridge multicast packet checksum validation"
This reverts commit 650ba2c21f20efe609b88aac64d25f055c922e26.

Fix a build failure due to upstream commit f39acc84aad1 ("net/sched:
act_vlan: Push skb->data to mac_header prior calling skb_vlan_*()
functions"), which came from an upstream stable update:

/tmp/kernel-henrix-uxQ5wmDx/build/net/sched/act_vlan.c: In function 'tcf_vlan':
  CC [M]  drivers/input/touchscreen/tsc2005.o
/tmp/kernel-henrix-uxQ5wmDx/build/net/sched/act_vlan.c:40:3: error: implicit declaration of function 'skb_push_rcsum' [-Werror=implicit-function-declaration]
   skb_push_rcsum(skb, skb->mac_len);

Signed-off-by: Luis Henriques <luis.henriques@canonical.com>